#!/bin/bash

source /home/centos/gitlab-runner/base.sh

terraform -chdir="${TERRAFORM_PATH}/aws-fedora-33-x86_64/" destroy -auto-approve "-state=states/${CUSTOM_ENV_CI_JOB_ID}.tfstate"

rm -rf "${TERRAFORM_PATH}/aws-fedora-33-x86_64/states/${CUSTOM_ENV_CI_JOB_ID}"
