#!/bin/bash

# cleanup is used to delete the instance. Terraform can handle that.

currentDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
# shellcheck source=./base.sh
source "${currentDir}/base.sh"
# Set the GCP credentials again for cleanup
export GOOGLE_APPLICATION_CREDENTIALS="${JOB}/gcp-credentials.json"

# we want to run as many commands as possible
set +e

section_start wait_logout "Wait for user logout"

# if a user is logged in to the runner, wait until they're done
waitForUserLogout

section_end wait_logout

section_start terraform_destroy "Terraform destroy and cleanup"

terraform-wrapper destroy -auto-approve

# Remove the host key from known_hosts.
VM_IP=$(cat "${JOB}/ip")
ssh-keygen -R "$VM_IP"

# Delete all job's data.
rm -rf "$JOB"

section_end terraform_destroy
