#!/bin/bash

function get_logs() {
  STDOUT_LEN=$(expr $(wc -c <${TERRAFORM_JOB}/stdout) + 1)
  $SSH "$(sshUser)@${VM_IP}" tail -c "$STDOUT_LEN" /tmp/gitlab-ci-stdout | tee -a ${TERRAFORM_JOB}/stdout

  STDERR_LEN=$(expr $(wc -c <${TERRAFORM_JOB}/stderr) + 1)
  $SSH "$(sshUser)@${VM_IP}" tail -c "$STDERR_LEN" /tmp/gitlab-ci-stderr | tee -a ${TERRAFORM_JOB}/stderr >&2

}

set -x

currentDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "${currentDir}/base.sh"

VM_IP=$($TERRAFORM output -json | jq -r .instance_ips.value[0])

scp "$1" "$(sshUser)@${VM_IP}:/tmp/gitlab-ci-script"
scp "${currentDir}/remote-exec" "$(sshUser)@${VM_IP}:/tmp/gitlab-ci-remote-exec"

$SSH "$(sshUser)@${VM_IP}" touch /tmp/gitlab-ci-stdout /tmp/gitlab-ci-stderr /tmp/gitlab-ci-status
$SSH "$(sshUser)@${VM_IP}" '/tmp/gitlab-ci-remote-exec >/tmp/gitlab-ci-exec-stdout 2>/tmp/gitlab-ci-exec-stderr &'

touch "${TERRAFORM_JOB}/stdout" "${TERRAFORM_JOB}/stderr"

while true; do
  get_logs

  STATUS=$($SSH "$(sshUser)@${VM_IP}" cat /tmp/gitlab-ci-status)
  if [[ "$STATUS" ]]; then
    get_logs

    $SSH "$(sshUser)@${VM_IP}" 'rm /tmp/gitlab-ci-*'
    rm ${TERRAFORM_JOB}/stdout ${TERRAFORM_JOB}/stderr
    exit "$STATUS"
  fi
done
